### ISSUE TITLE
Configurable default behaviour of HTML escaping

### ISSUE THREAD

**Issue by igor-lobanov** [vti/text-caml#20]
What do you think about adding configuration option to set default behavior as non-escaping? Some templates are used in HTML documents and current behavior is appropriate. But sometimes it's required to use templates for other types of documents.

'&' usage of course solves this issue but making non-escaping behavior default for such cases looks more handy.

```perl
my $view = Text::Caml->new(do_no_escape => 1);
```

'&' can be switcher in this case:

```perl
    my $do_not_escape = $self->{do_not_escape};
    if ($tag =~ s/\A \&//xms) {
        $do_not_escape = !$do_not_escape;
    }
```

**Comment by vti** [comment]
I totally agree. Could you prepare a PR?
